#import "lib.typ": *

#let tip(type: "Tip", title: none, icon: emoji.lightbulb, align-icon: center + horizon, icon-color: luma(0%), bar: gray, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let tip-colored(type: "Tip", title: none, icon: emoji.lightbulb, align-icon: center + horizon, icon-color: luma(0%), bar: yellow, background-color: yellow.lighten(60%), border: yellow, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let info(type: "Info", title: none, icon: emoji.info, align-icon: center + horizon, icon-color: blue, bar: blue, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let info-colored(type: "Info", title: none, icon: emoji.info, align-icon: center + horizon, icon-color: blue, bar: blue, background-color: blue.lighten(80%), border: blue, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let important(type: "Important", title: none, icon: emoji.excl, align-icon: center + horizon, icon-color: luma(0%), bar: red, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: red, text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let important-colored(type: "Important", title: none, icon: emoji.excl, align-icon: center + horizon, icon-color: luma(0%), bar: red, background-color: red.lighten(80%), border: red, radius: 1em, inset: (:), breakable: true, text-color: red, text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let warning(type: "Warning", title: none, icon: emoji.warning, align-icon: center + horizon, icon-color: luma(0%), bar: luma(0%), background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let warning-colored(type: "Warning", title: none, icon: emoji.warning, align-icon: center + horizon, icon-color: luma(0%), bar: luma(0%), background-color: yellow.lighten(40%), border: luma(0%), radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let caution(type: "Caution", title: none, icon: emoji.fire, align-icon: center + horizon, icon-color: luma(0%), bar: orange, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let caution-colored(type: "Caution", title: none, icon: emoji.fire, align-icon: center + horizon, icon-color: luma(0%), bar: orange, background-color: orange.lighten(60%), border: orange, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let danger(type: "Danger", title: none, icon: emoji.bomb, align-icon: center + horizon, icon-color: luma(0%), bar: luma(0%), background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let danger-colored(type: "Danger", title: none, icon: emoji.bomb, align-icon: center + horizon, icon-color: luma(0%), bar: luma(0%), background-color: black.lighten(60%), border: luma(0%), radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let construction(type: "Under Construction", title: none, icon: emoji.construction, align-icon: center + horizon, icon-color: luma(0%), bar: luma(0%), background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let construction-colored(type: "Under Construction", title: none, icon: emoji.construction, align-icon: center + horizon, icon-color: luma(0%), bar: yellow, background-color: black.lighten(80%), border: yellow, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let note(type: "Note", title: none, icon: emoji.page.pencil, align-icon: center + horizon, icon-color: luma(0%), bar: gray, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let note-colored(type: "Note", title: none, icon: emoji.page.pencil, align-icon: center + horizon, icon-color: luma(0%), bar: gray, background-color: gray.lighten(60%), border: gray, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let talk(type: "Talk", title: none, icon: emoji.bubble.speech, align-icon: center + horizon, icon-color: luma(0%), bar: aqua, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let talk-colored(type: "Talk", title: none, icon: emoji.bubble.speech, align-icon: center + horizon, icon-color: luma(0%), bar: aqua, background-color: aqua.lighten(80%), border: aqua, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let alert(type: "Alert", title: none, icon: emoji.siren, align-icon: center + horizon, icon-color: luma(0%), bar: red, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let alert-colored(type: "Alert", title: none, icon: emoji.siren, align-icon: center + horizon, icon-color: luma(0%), bar: red, background-color: red.lighten(80%), border: red, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let experiment(type: "Experiment", title: none, icon: emoji.testtube, align-icon: center + horizon, icon-color: luma(0%), bar: olive, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let experiment-colored(type: "Experiment", title: none, icon: emoji.testtube, align-icon: center + horizon, icon-color: luma(0%), bar: olive, background-color: olive.lighten(80%), border: olive, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let snippet(type: "Snippet", title: none, icon: emoji.laptop, align-icon: center + horizon, icon-color: luma(0%), bar: eastern, background-color: none, border: (:), radius: (:), inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)

#let snippet-colored(type: "Snippet", title: none, icon: emoji.laptop, align-icon: center + horizon, icon-color: luma(0%), bar: eastern, background-color: eastern.lighten(80%), border: eastern, radius: 1em, inset: (:), breakable: true, text-color: luma(0%), text-spacing: 1.2em, body) = admonition(type: type, title: title, text-spacing: text-spacing, icon: icon, align-icon: align-icon, icon-color: icon-color, bar: bar, background-color: background-color, border: border, radius: radius, inset: inset, breakable: breakable, text-color: text-color, body)